### ISSUE TITLE
unexpected signal during runtime execution

### ISSUE THREAD

**Issue by amitnarang28** [briangann/predix-chisel-postgres#4]
Hi 

I am constantly getting this kind of error on mac while running the client program and it kill the chisel connection.
Is there any thing I have to do to avoid these errors?

```
2017/04/06 11:12:29 client: Sending configurating
2017/04/06 11:12:29 client: Connected (Latency 158.39653ms)
2017/04/06 11:13:44 client: Disconnected
1969/12/31 19:00:00 client: Retrying in 100ms...
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xb9210a94c55 pc=0xcd170]

goroutine 20 [running]:
runtime.throw(0x4feac0, 0x2a)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:547 +0x90 fp=0xc82040b620 sp=0xc82040b608
runtime.sigpanic()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc82040b670 sp=0xc82040b620
sync.(*Pool).Get(0x68f670, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/sync/pool.go:102 +0x40 fp=0xc82040b6c0 sp=0xc82040b670
fmt.newPrinter(0x10)
	/usr/local/Cellar/go/1.6.2/libexec/src/fmt/print.go:133 +0x27 fp=0xc82040b700 sp=0xc82040b6c0
fmt.Fprintf(0xa04a80, 0xc820366dc0, 0x4b80a0, 0x10, 0xc82040b8d8, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/fmt/print.go:187 +0x30 fp=0xc82040b748 sp=0xc82040b700
```

**Comment by amitnarang28** [comment]
I am able to resolve this issue using by building the chisel from source.
I downloaded the latest version of go lang from https://golang.org/ which is 1.8 where as the current version of executables are compiled with version 1..6.2 which has this bug.

If possible please update the binaries with latest compiled version.

Thanks
